"""Boss-Wissen fuer die Solo-Abenteuer (Book of Heroes).

Quellen: Hearthstone Wiki (hearthstone.wiki.gg), Hearthstone Top Decks, Icy Veins (Stand 2020/21 - einzelne
Zahlen koennen durch Patches veraltet sein). `win_verified=True` heisst: die Siegschwelle steht im Wiki.

Felder
  match      Hero-Karten-IDs des Bosses (Log: CARDTYPE HERO des Gegners)
  win_hp     Der Kampf endet, sobald der Boss <= diesen Wert hat (z.B. 10 bei Archimonde/Jaina)
  survive    Ziel ist Ueberleben fuer N Runden (kein Sieg durch Schaden)
  bias       Feinjustierung der Regel-Engine:
             hp_bonus  Zusatzwert fuer jede Heldenkraft-Nutzung
             face      Faktor fuer Schaden zum Boss-Helden (1.0 = normal)
             priority  Name -> Faktor: gegnerische Diener mit diesem Namen zuerst loswerden
             reserve   Kartenname -> (nur auf Ziel mit diesem Namen, Strafe): Karte aufheben
             defensive Sicherheit wichtiger als Schaden
"""

SRC_WIKI = "Hearthstone Wiki"
SRC_TOP = "Hearthstone Top Decks"
SRC_ICY = "Icy Veins"

BOSSES = [
    # ---------------------------------------------------------------- Jaina (Magierin), Story_01
    dict(id="jaina_antonidas", match=["Story_01_Antonidas"], name="Erzmagier Antonidas", chapter="Jaina", order=1,
         start_hp=30, boss_power="Passiv: seine Zauber wirken doppelt",
         goal="Brett sauber halten und ihn niederringen (er hat keine Schadenszauber)",
         tips=["Dein Heldenkraft: 2 Mana, 1 Schaden.",
               "Sein Deck zieht viel und füllt die Hand; Echo von Medivh kopiert sein Board - halte es klein und leer.",
               "Mit leerem Board läuft er irgendwann in die Erschöpfung.",
               "Alternativer Sieg: Spiegelbilder auf sein Board bringen (Duplizieren, Geschmolzenes Spiegelbild), bis es 7 Diener sind, dann nur noch Frostblitz/Feuerball auf ihn - die Spiegelbilder nicht töten."],
         mulligan=["Frostblitz", "Graue Katze", "Wasserelementar"],
         dangers=["Echo von Medivh kopiert sein Board", "Arcane Explosion (2 Schaden) und Twilight Flamecaller töten kleine Diener"],
         bias=dict(), source=SRC_TOP + ", " + SRC_WIKI),
    dict(id="jaina_kaelthas", match=["Story_01_Kaelthas"], name="Prinz Kael'thas", chapter="Jaina", order=2,
         start_hp=30, boss_power="Passiv (Firemancy): nach jedem Zauber kommt ein um 2 teurerer Feuerball in sein Deck",
         goal="Board einfrieren und mit der Heldenkraft jede Runde Schaden zum Gesicht machen",
         tips=["Dein Heldenkraft: 2 Mana, 2 Schaden - jede Runde ins Gesicht, Kael'thas heilt sich nicht.",
               "Board einfrieren, ein bis zwei Diener legen, am Ende mit Eiskugeln abschließen.",
               "Eisblock und Gegenzauber helfen gegen die späten Feuerbälle.",
               "Dein Leben nicht auf 12 oder weniger fallen lassen."],
         mulligan=[], dangers=["späte Feuerbälle", "zu viel Schaden durch Diener"],
         bias=dict(hp_bonus=2.0, face=1.3), source=SRC_TOP + ", " + SRC_WIKI),
    dict(id="jaina_arthas", match=["Story_01_Arthas"], name="Prinz Arthas", chapter="Jaina", order=3,
         start_hp=30, boss_power="Defensive Strike (2 Mana): 2 Schaden an alle deine Diener; stirbt einer, bekommen seine Diener Gottesschild",
         goal="Anfangs mit der Heldenkraft das Board kontrollieren, danach 3 Schaden pro Runde ins Gesicht",
         tips=["Dein Heldenkraft: 2 Mana, 3 Schaden (Eisblitz Rang 3).",
               "Diener mit wenig Leben meiden (Zauberlehrling ist hier schwach).",
               "Flammenstoß einsetzen, wenn sich genug Diener angesammelt haben.",
               "Noble Sacrifice fängt deinen ersten großen Treffer ab; er heilt sich."],
         mulligan=[], dangers=["Noble Sacrifice blockt den ersten großen Treffer", "seine Heilung"],
         bias=dict(), source=SRC_TOP + ", " + SRC_WIKI),
    dict(id="jaina_grommash", match=["Story_01_Grommash"], name="Grommash Höllschrei", chapter="Jaina", order=4,
         start_hp=30, boss_power="Ab Runde 5 (5 Mana): Gorehowl anlegen",
         goal="Ab Runde 4 jede Runde einen Wasserelementar beschwören, damit Grommash eingefroren bleibt",
         tips=["Dein Heldenkraft (4 Mana): Wasserelementar beschwören - ab Runde 4 jede Runde.",
               "Restmana für billige Karten nutzen; mit Feuerball verbrennen, mit Dienern abschließen.",
               "Thrall hilft per Skript in den Runden 7, 9, 10 und 12 mit Voltaic Burst und Geisterwolf."],
         mulligan=[], dangers=["Gorehowl (ca. 7 Schaden pro Schlag)", "Warpath und Brawl räumen dein Board"],
         bias=dict(hp_bonus=2.0), source=SRC_TOP + ", " + SRC_WIKI),
    dict(id="jaina_archimonde", match=["Story_01_Archimonde"], name="Archimonde", chapter="Jaina", order=5,
         start_hp=40, win_hp=10, win_verified=True,
         boss_power="Chaosregen (6 Mana): ruft 2 Höllenbestien (6/6) herbei",
         goal="Archimonde auf 10 Leben oder weniger bringen - dann beenden Thrall, Tyrande und Nordrassil den Kampf",
         tips=["Dein Heldenkraft (4 Mana): Wasserelementar 4/7 - ab der 4. Runde möglichst jede Runde.",
               "Frühe Runden: seine kleinen Dämonen großzügig mit Einzelentfernung (Froststrahl, Frostblitz) wegräumen.",
               "Chaosregen: Höllenbestien mit Frostnova (oder zweimal Froststrahl) einfrieren, sie greifen dann nicht an.",
               "Verwandlung oder Zertrümmern für den großen Spott-Diener Belagerungsbrecher aufheben.",
               "Der Boss spielt Karten ab 5 Mana lieber als Chaosregen - in deinen Partien kam sie ab Runde 12 trotzdem fast jede zweite Runde.",
               "Dein Ziel ist nur 10 Leben - früh Druck machen statt jede Bestie einzeln zu töten."],
         mulligan=["Frostblitz", "Froststrahl", "Frostnova"],
         dangers=["Dämonenschwarm früh", "Belagerungsbrecher (Spott)", "mehrere Höllenbestien auf einmal"],
         bias=dict(hp_bonus=2.0, face=1.4, priority={"Belagerungsbrecher": 1.4},
                   reserve={"Verwandlung": ("Belagerungsbrecher", 5.0), "Zertrümmern": ("Belagerungsbrecher", 3.0)}),
         source=SRC_WIKI + ", " + SRC_TOP + ", " + SRC_ICY),
    dict(id="jaina_garrosh", match=["Story_01_Garrosh"], name="Garrosh Höllschrei", chapter="Jaina", order=6,
         start_hp=40, boss_power="Horde Armada (0 Mana): 4 Schaden auf die Tore von Theramore",
         goal="Die Tore halten und mit Wasserelementaren (5/8) das Board kontrollieren",
         tips=["Du startest mit vier Toren von Theramore (0/10, Spott); jedes hält etwa 3 Treffer.",
               "Dein Heldenkraft: Wasserelementar Rang 3 (5/8) - ab Runde 4 jede Runde.",
               "Schiffskanone und Skybarge sind deine besten Karten; Staff of Antonidas ist zu langsam."],
         mulligan=["Violette Zauberschwinge", "Elementar der Kirin Tor", "Schuppenreiterin"],
         dangers=["Sturmangriff-Diener und Piratenschaden zerstören früh die Tore", "jedes Tor verursacht beim Sterben 3 Schaden an dir (insgesamt 12)"],
         bias=dict(hp_bonus=2.0), source=SRC_TOP + ", " + SRC_ICY),
    dict(id="jaina_thrall", match=["Story_01_Thrall"], name="Thrall", chapter="Jaina", order=7,
         start_hp=50, boss_power="Gibt seinen Dienern Windzorn (2 Mana)",
         goal="Kontrollspiel: jede Runde sein Board einfrieren/räumen, nicht racen",
         tips=["Dein Heldenkraft (3 Mana): 2 Schaden an 2 zufällige Diener und einfrieren.",
               "Erst seine beiden Erdbeben herauslocken, dann den Fokussierungsiris legen.",
               "Nicht stalle-und-töte: Heilender Regen und Walking Fountain heilen ihn.",
               "Wandelnder Brunnen (Lebensraub + Windzorn) hat in einer verlorenen Partie Thrall von 15 auf über 30 Leben geheilt und dich in zwei Zügen von 30 auf 10 geschlagen: sofort ausschalten (vernichten, verwandeln, schweigen; Einfrieren hilft nur eine Runde), nicht erst an den Spott-Dienern vorbei ins Gesicht spielen.",
               "Spät kommen Gewittersturm (räumt dein Board) und ein Frostwolfkriegsfürst, der bis 9/9 wächst: nicht jedes Mal alles ausspielen, Karten für nach dem Sturm halten.",
               "Mit einem leeren eigenen Brett gegen mehrere Gegner-Diener keine zwei kleinen Diener hinlegen, die sofort sterben - erst Brett stabilisieren (Fokussierungsiris, Heldenkraft)."],
         mulligan=[], dangers=["große Diener mit Windzorn", "Feuerelementar und Schicksalshammer",
                               "Wandelnder Brunnen: heilt Thrall bei jedem Treffer, mit Windzorn doppelt",
                               "Gewittersturm räumt dein Board", "Frostwolfkriegsfürst wird riesig (bis 9/9)"],
         bias=dict(priority={"Wandelnder Brunnen": 2.2, "Frostwolfkriegsfürst": 1.4}, defensive=True),
         source=SRC_TOP + ", " + SRC_ICY + ", eigene Partie-Auswertung"),
    dict(id="jaina_aethas", match=["Story_01_Aethas"], name="Aethas Sonnenhäscher", chapter="Jaina", order=8,
         start_hp=50, boss_power="2 Mana: 3 Schaden an deinen Helden und +2 Zauberschaden in diesem Zug",
         goal="Früh Tempo machen, sein Board einfrieren/räumen, spät mit Feuerball/Pyroblast abschließen",
         tips=["Seine Geheimnisse (Gegenzauber, Explosive Runen, Flame Ward) in der Mitte des Spiels auslösen, damit der Wolkenprinz nie aktiv wird.",
               "Spät: Meteor oder Flammenstoß; Druck mit Erzmagier Kalec, Violet Warden, Arkanriese oder Staff of Antonidas.",
               "Vermeide unnötigen Schaden - die 2 Heldenkraft-Schaden pro Runde sind unvermeidlich.",
               "Köder: Hat er ein Geheimnis, zuerst einen billigen Zauber wirken (der Gegenzauber fängt den ersten Zauber ab), erst dann Flammenstoß oder Pyroschlag. In einer verlorenen Partie hat ein Gegenzauber den Flammenstoß (7 Mana) verschluckt und das Spiel gekippt.",
               "Explosive Runen bestrafen frisch gespielte Diener: bei offenem Geheimnis lieber nichts Wertvolles legen."],
         mulligan=[], dangers=["späte Feuerbälle von oben gezogen", "Wolkenprinz",
                               "Gegenzauber fängt den ersten Zauber des Zuges ab", "Explosive Runen gegen deine Diener"],
         bias=dict(secret_p=0.5), source=SRC_TOP + ", eigene Partie-Auswertung"),

    # ---------------------------------------------------------------- Garrosh (Krieger), Story_03 (nur Teilwissen)
    dict(id="garrosh_anduin", match=["Story_03_Anduin"], name="Prinz Anduin Wrynn", chapter="Garrosh", order=7,
         start_hp=50, boss_power="Harmonic Mallet",
         goal="Kontrollspiel gegen einen Priester mit Spott und Heilung",
         tips=["Hohe-Leben-Diener nehmen, um seine Heldenkraft zu überstehen."],
         mulligan=[], dangers=["Spott-Diener und Heilung (Göttlicher Hymnus)"], bias=dict(), source=SRC_ICY),
    dict(id="garrosh_thrall", match=["Story_03_Thrall"], name="Thrall", chapter="Garrosh", order=8,
         start_hp=50, boss_power="Gorehowl, später Herz von Y'Shaarj (nach 6 getöteten Dienern)",
         goal="Midrange-Schamane besiegen",
         tips=["Vor Abschluss der Quest noch eine Waffe anlegen - danach geht Gorehowl verloren."],
         mulligan=[], dangers=[], bias=dict(), source=SRC_ICY),

    # ---------------------------------------------------------------- Uther (Paladin), Story_04 (nur Teilwissen)
    dict(id="uther_doomhammer", match=["Story_04_Doomhammer"], name="Orgrim Schicksalshammer", chapter="Uther", order=2,
         start_hp=50, boss_power="", goal="Früh mit Brazen Zealot starten und ihn buffen",
         tips=["In Runde 8 wirkt der Boss Gul'dan's Reinforcements und zerstört sein eigenes Board."],
         mulligan=[], dangers=[], bias=dict(), source=SRC_ICY),
    dict(id="uther_saurfang", match=["Story_04_Saurfang"], name="Varok Saurfang", chapter="Uther", order=3,
         start_hp=50, boss_power="", goal="Deine Librams so schnell wie möglich verbilligen",
         tips=["Lordaeron Attendant und Radiant Lightspawn machen Librams billiger."],
         mulligan=[], dangers=[], bias=dict(), source=SRC_ICY),
    dict(id="uther_darkportal", match=["Story_04_DarkPortal"], name="Das Dunkle Portal", chapter="Uther", order=4,
         start_hp=100, boss_power="", goal="Überleben",
         tips=["Mit Weihe das Board räumen, bevor du Bombard Portal einsetzt."],
         mulligan=[], dangers=[], bias=dict(defensive=True), source=SRC_ICY),
    dict(id="uther_arthas", match=["Story_04_Arthas"], name="Prinz Arthas", chapter="Uther", order=8,
         start_hp=300, survive=13, boss_power="", goal="Nicht töten, sondern 13 Runden überleben",
         tips=["Der Kampf endet nach 13 Runden - Sicherheit geht vor Schaden."],
         mulligan=[], dangers=[], bias=dict(defensive=True), source=SRC_ICY),

    # ---------------------------------------------------------------- Anduin (Priester), Story_05 (nur Teilwissen)
    dict(id="anduin_varian", match=["Story_05_Varian"], name="König Varian", chapter="Anduin", order=1,
         start_hp=30, boss_power="", goal="Das Board so schnell wie möglich fluten",
         tips=["Der Boss hat keine Flächenentfernung."], mulligan=[], dangers=[], bias=dict(), source=SRC_ICY),
    dict(id="anduin_jaina", match=["Story_05_Jaina"], name="Jaina Prachtmeer", chapter="Anduin", order=2,
         start_hp=30, boss_power="", goal="Erst ein kleines Board aufbauen, dann Entfernung einsetzen",
         tips=["Sie spielt Frostblitz und Arkanriesen.", "Mit Robes of Protection nimmst du ihrer Heldenkraft und ihren Zaubern das Ziel."],
         mulligan=[], dangers=[], bias=dict(), source=SRC_ICY),

    # ---------------------------------------------------------------- Thrall (Schamane), Story_07
    dict(id="thrall_blackmoore", match=["Story_07_Blackmoore_001hb"], name="Aedelas Schwarzmoor", chapter="Thrall", order=1,
         start_hp=30, boss_power="Heilt seine Diener, ruft 3/2- und 2/1-Soldaten",
         goal="Kleine Diener früh besiegen", tips=["Die gefangene Krokilisk bekommt +1 Angriff pro Runde - sie setzt dir eine Uhr.",
                                                    "Flächenentfernung für den Oger (4/15) aufheben."],
         mulligan=[], dangers=["wachsende Krokilisk"], bias=dict(), source=SRC_TOP),
    dict(id="thrall_drekthar", match=["Story_07_DrekThar_002hb"], name="Drek'Thar", chapter="Thrall", order=2,
         start_hp=30, boss_power="Fünf Elementar-Unterbosse mit Immunitäten",
         goal="Jeden Elementar mit passendem Zauber besiegen",
         tips=["Geist des Feuers ist gegen Feuer immun, Geist des Wassers gegen Frost, Geist der Wildnis gegen Natur.",
               "Geist der Erde und der Luft heilen Thrall jeweils um 15, wenn sie besiegt werden - nicht überstürzen."],
         mulligan=[], dangers=[], bias=dict(), source=SRC_TOP),
    dict(id="thrall_stranger", match=["Story_07_Stranger_003hb", "Story_07_Stranger_003hb2"], name="Mysteriöser Fremder (Orgrim)", chapter="Thrall", order=3,
         start_hp=30, boss_power="", goal="Seinen Vorsprung nach Schicksalshammer (4 Mana) ausnutzen",
         tips=["Er verbraucht 4 Mana für den Schicksalshammer - in der Zeit Tempo machen."],
         mulligan=[], dangers=["Schicksalshammer"], bias=dict(), source=SRC_TOP),
    dict(id="thrall_mannoroth", match=["Story_07_Mannoroth_004hb"], name="Mannoroth", chapter="Thrall", order=4,
         start_hp=50, boss_power="Senkt das Leben deiner Diener um 2 (auch unter 0)",
         goal="Diener auf der Kurve spielen", tips=["Seine Heldenkraft kann dein Board leerräumen - nicht alles auf einmal legen."],
         mulligan=[], dangers=["Heldenkraft räumt Diener mit wenig Leben"], bias=dict(), source=SRC_TOP),
    dict(id="thrall_archimonde", match=["Story_07_Archimonde_005hb"], name="Archimonde (Thrall)", chapter="Thrall", order=5,
         start_hp=50, win_hp=1, win_verified=True, boss_power="Chaosregen ab Runde 6",
         goal="Früh Board aufbauen; der Kampf ist teilweise geskriptet",
         tips=["Garantierte Startkarten: Far Sight, Lightning Storm, Heilender Regen.",
               "Skript: Runde 3 Frostnova, Runde 5 Tiefe Gefrierung durch Jaina, danach rettet Nordrassil."],
         mulligan=[], dangers=["Chaosregen ab Runde 6"], bias=dict(), source=SRC_WIKI + ", " + SRC_TOP),
    dict(id="thrall_deathwing", match=["Story_07_Deathwing_006hb", "Story_07_Deathwing_006hb2", "Story_07_Deathwing_006hb3"],
         name="Todesschwinge", chapter="Thrall", order=6, start_hp=200, boss_power="Schwächt dich ab 100 und 50 Leben",
         goal="Großes Board bauen und ihn in ein bis zwei Runden töten",
         tips=["Ab 100 Leben vernichtet seine Heldenkraft deinen linken Diener und eine Handkarte, ab 50 zusätzlich eine Karte vom Nachziehstapel.",
               "Vier Drachenaspekte unterstützen ihn (Alexstrasza belebt dich 3-mal, Nozdormu setzt alle auf 10 Mana)."],
         mulligan=[], dangers=["Heldenkraft-Eskalation bei 100 und 50 Leben"], bias=dict(), source=SRC_TOP),
    dict(id="thrall_jaina", match=["Story_07_Jaina_007hb"], name="Jaina (Thrall)", chapter="Thrall", order=7,
         start_hp=50, boss_power="Wechselnde Heldenkraft, Wasserelementare ab 40 Leben",
         goal="Früh Board aufbauen und sie in die Erschöpfung zwingen", tips=["Erdbeben und Heilender Regen sind deine Schlüsselkarten."],
         mulligan=[], dangers=["Elementare der Kirin Tor machen billige Zauber zu Burst"], bias=dict(), source=SRC_TOP),
    dict(id="thrall_garrosh", match=["Story_07_Garrosh_008hb"], name="Garrosh (Thrall)", chapter="Thrall", order=8,
         start_hp=50, boss_power="Gorehowl früh", goal="Elementare weiter aufbauen",
         tips=["Wenig Heilung oder Flächenentfernung nötig - sein Kartenpool ist schwach.",
               "Kopierter Geisterwolf fängt die ersten Gorehowl-Schläge ab."],
         mulligan=[], dangers=["Gorehowl"], bias=dict(), source=SRC_TOP),

    # ---------------------------------------------------------------- Gul'dan (Hexenmeister), Story_09
    dict(id="guldan_warrior", match=["Story_09_Warrior_001hb"], name="Vergessener Krieger", chapter="Gul'dan", order=1,
         start_hp=30, survive=9, boss_power="", goal="9 Runden überleben",
         tips=["Board sauber halten, mit der Heldenkraft heilen."], mulligan=[], dangers=[],
         bias=dict(defensive=True), source=SRC_TOP),
    dict(id="guldan_throne", match=["Story_09_Throne_002hb"], name="Thron der Elemente", chapter="Gul'dan", order=2,
         start_hp=30, boss_power="", goal="8 Schamanenzauber spielen",
         tips=["Frühe Entfernung nicht verbrauchen und nicht ausspielen wie auf der Kurve.", "Marschbrut-Effekt nutzen, um zusätzliche Schamanenzauber zu erzeugen."],
         mulligan=[], dangers=[], bias=dict(), source=SRC_TOP),
    dict(id="guldan_nerzhul", match=["Story_09_Nerzhul_003hb"], name="Ner'zhul", chapter="Gul'dan", order=3,
         start_hp=30, boss_power="", goal="Mit Elementar-Synergie spät gewinnen",
         tips=["Genug Elementar-Synergie ziehen, dann Verteidigung und Finisher nutzen."],
         mulligan=[], dangers=[], bias=dict(), source=SRC_TOP),
    dict(id="guldan_blackhand", match=["Story_09_Blackhand_004hb"], name="Häuptlinge der Horde (Rätsel)", chapter="Gul'dan", order=4,
         start_hp=30, boss_power="", goal="Jedes Rätsel mit der festen Zugfolge lösen",
         tips=["Grommash: Imps gegen Hellboars tauschen, Shadow Bolt auf den 4/4-Orc, Heldenkraft.",
               "Blackhand: drei Dragon Eggs, Animated Broomstick, Heldenkraft.",
               "Durotan: Hellfire, Shadow Council, drei Felhounds tauschen, Heldenkraft.",
               "Kilrogg: Dunemaul Shaman tauscht in beide Orcs, Grimoire of Sacrifice auf den Imp, Heldenkraft.",
               "Hurkan: Curse of Weakness (einmal), Firebirds in zwei Taunt-Orcs tauschen, Drain Soul auf einen Orc, Lake Thresher angreifen, Heldenkraft.",
               "Zuluhed: zwei Darkglares, Locust-Tausch, Fiendish Circle, Animated Broomstick, Darkest Hour, Batterhead gegen den Taunt, beide Münzen, Heldenkraft.",
               "Kargath: zwei Raven Familiars, Soularium, Taunts mit zwei 6/6 tauschen, Demon Fire und Batterhead gegen die Kisten, beide Münzen, zweites Soularium, Heldenkraft.",
               "Fenris: Felhound, Flame Imp, Deathweb Spider, Animated Broomstick, dann die Tauschfolge (Imp, Spider, drei Cobras, Felhound), Heldenkraft."],
         mulligan=[], dangers=["Abweichen von der festen Reihenfolge"], bias=dict(), source=SRC_TOP),
    dict(id="guldan_medivh", match=["Story_09_Medivh_005hb"], name="Medivh", chapter="Gul'dan", order=5,
         start_hp=50, boss_power="Atiesh", goal="Seine Erzmagier-Lehrlinge zuerst entfernen",
         tips=["Dein Heldenkraft (4 Mana): ersetzt einen gegnerischen Diener durch einen eigenen Dämon.",
               "Archmage's Apprentice höchste Priorität, mindestens zwei Flammenstöße im Deck des Bosses.",
               "Spät racen, sobald deine Hand fast leer ist."],
         mulligan=[], dangers=["Atiesh-Wertmaschine", "Flammenstoß"], bias=dict(priority={"Lehrling des Erzmagiers": 1.6}), source=SRC_TOP),
    dict(id="guldan_orgrim", match=["Story_09_Orgrim_004hb", "Story_09_Orgrim_006hb"], name="Orgrim Schicksalshammer", chapter="Gul'dan", order=6,
         start_hp=50, survive=13, boss_power="", goal="13 Runden überleben",
         tips=["Frühe Karten sind schwach - verlass dich auf die Heldenkraft.", "Mittelspiel-Legendäre (Rexxar, Saurfang, Schicksalshammer), später Grommash-Schaden."],
         mulligan=[], dangers=["Legendäre Welle im Mittelspiel", "Grommash im Endspiel"], bias=dict(defensive=True), source=SRC_TOP),
    dict(id="guldan_tombguardian", match=["Story_09_TombGuardian_008hb"], name="Grabwächter", chapter="Gul'dan", order=8,
         start_hp=100, boss_power="Auge von Sargeras: zerstört alle zwei Runden Manakristalle (immer +1)",
         goal="Starke Karten früh spielen, solange du Mana hast",
         tips=["Du startest mit 10 Mana.", "Stormreaver-Hexenmeister kopiert Zauberschaden-Zauber (Spellburst).",
               "Schulgeister und Kaskadierendes Verhängnis für die Boardkontrolle aufheben."],
         mulligan=[], dangers=["Mana wird jede zweite Runde zerstört", "große Lebenspunkte"], bias=dict(), source=SRC_TOP),

    # ---------------------------------------------------------------- Illidan (Dämonenjäger), Story_10
    dict(id="illidan_arthas1", match=["Story_10_Arthas_001hb"], name="Prinz Arthas", chapter="Illidan", order=1,
         start_hp=30, boss_power="Frostmourne", goal="Board räumen und Frostmourne-Treffer vermeiden",
         tips=["Festering Ghouls wachsen mit den gestorbenen Dienern."], mulligan=[], dangers=["Festering Ghouls", "Frostmourne"], bias=dict(), source=SRC_TOP),
    dict(id="illidan_tichondrius", match=["Story_10_TIchondrius_002hb"], name="Tichondrius", chapter="Illidan", order=2,
         start_hp=40, boss_power="", goal="Phase 1: Board kontrollieren (nicht töten); Phase 2 mit dem Schädel: ihn überholen",
         tips=["Phase 1 endet nach insgesamt 40 Schaden an Gegnern.", "Nach dem Schädel ändert sich deine Heldenkraft stark."],
         mulligan=[], dangers=["Soulwringer-Kopien", "zu schnelles Ziehen führt zur Erschöpfung"], bias=dict(), source=SRC_TOP),
    dict(id="illidan_maiev", match=["Story_10_Maiev_003hb"], name="Maiev Schattensang", chapter="Illidan", order=3,
         start_hp=50, boss_power="Warden's Glaive: versetzt einen Diener samt Nachbarn in den Ruhezustand",
         goal="Gesund bleiben und mit Lebensraub heilen", tips=["Nagas entdecken und Todesröcheln-Wert aufbauen.", "Mur'gul Reaver früh spielen."],
         mulligan=[], dangers=["Glefe umgeht Spott", "aggressiver Druck"], bias=dict(defensive=True), source=SRC_TOP),
    dict(id="illidan_malfurion", match=["Story_10_Malfurion_004hb", "Story_10_Velas_004hb"], name="Malfurion Sturmgrimm / Velas", chapter="Illidan", order=4,
         start_hp=50, boss_power="", goal="Board klar halten bis Phase 2 (50 ausgegebene Mana verbünden dich mit Malfurion)",
         tips=["Blood Elf Allies nicht spielen."], mulligan=[], dangers=[], bias=dict(), source=SRC_TOP),
    dict(id="illidan_magtheridon", match=["Story_10_Magtheridon_005hb"], name="Magtheridon", chapter="Illidan", order=5,
         start_hp=100, boss_power="Diener mit 2 Leben sterben und rufen Diener aus seiner Hand",
         goal="Mit wiederkehrenden Verbündeten abnutzen und gesund bleiben",
         tips=["Er startet mit zwei Voidlords.", "Nicht zu viele Karten ziehen (Erschöpfung)."],
         mulligan=[], dangers=["Erschöpfung durch zu viel Kartenziehen"], bias=dict(), source=SRC_TOP),
    dict(id="illidan_anubarak", match=["Story_10_Anubarak_006hb"], name="Anub'arak", chapter="Illidan", order=6,
         start_hp=50, boss_power="", goal="Gesundheit mit Sulking Imp und Ruthless Wrathguard auffüllen",
         tips=["Gilt als der leichteste Boss dieses Kapitels."], mulligan=[], dangers=[], bias=dict(), source=SRC_TOP),
    dict(id="illidan_dkarthas", match=["Story_10_Arthas_007hb"], name="Todesritter Arthas", chapter="Illidan", order=7,
         start_hp=30, boss_power="Vier Obelisken", goal="Die drei Obelisken auf seiner Seite zerstören",
         tips=["Er holt sich danach alle vier zurück - ein Ein-Zug-Kill ist nicht nötig."], mulligan=[], dangers=[], bias=dict(), source=SRC_TOP),
    dict(id="illidan_akama", match=["Story_10_Akama_008hb"], name="Akama", chapter="Illidan", order=8,
         start_hp=60, boss_power="", goal="Über mehrere Runden ein Combo-Board bauen und Akama töten; danach noch 4 Runden gegen Maiev überleben",
         tips=["Akamas Deck hat fast keine Flächenentfernung.", "Mit gesundem Board in den Maiev-Kampf gehen."],
         mulligan=[], dangers=["Maiev zieht jede Runde nach"], bias=dict(), source=SRC_TOP),

    # ---------------------------------------------------------------- Book of Heroes: Rexxar, Garrosh, Uther, Anduin (Icy Veins, Okt. 2020)
    dict(id="rexxar_leoroxx", match=["Story_02_Leoroxx"], name="Leoroxx", chapter="Rexxar", order=1,
         start_hp=30, boss_power="Tadeln (2 Mana): senkt den Angriff eines Dieners einen Zug lang um 1",
         goal="Er setzt dich nicht unter Druck und baut auf Jäger-Geheimnisse - spiel sicher um sie herum und räume sein Brett",
         tips=["Mit dem schwächsten Diener zuerst angreifen: so verlierst du keinen großen Diener an die Eisige Falle und nimmst nicht den vollen Schaden von Irreführung.",
               "Diener mit höchstens 2 Leben erst tauschen, bevor sie ins Gesicht gehen (Sprengfalle).",
               "Deine Karte Haratha (Mulligan: behalten) ist stark."],
         mulligan=["Springpaw", "Tierruf", "Eisenfell-Grizzly", "Haratha"], dangers=["Sprengfalle gegen kleine Diener", "Irreführung"],
         bias=dict(secret_p=0.4), source=SRC_ICY),
    dict(id="rexxar_blackhand", match=["Story_02_Blackhand"], name="Häuptling Schwarzfaust", chapter="Rexxar", order=2,
         start_hp=30, boss_power="Schwarzfaust (2 Mana): vernichtet einen zufälligen verletzten feindlichen Diener",
         goal="Er sammelt Rüstung und entfernt dein Brett: maximal Gesichtsschaden, Diener gehen jede Runde ins Gesicht",
         tips=["Spät im Spiel mit Ballistenschuss die Rüstung wegnehmen, Rest-Diener beenden das Spiel.",
               "Zauber (Flankenstoß, Mehrfachschuss) für sein Brett, Diener ins Gesicht."],
         mulligan=["Springpaw", "Aasfressende Hyäne", "Tiergefährte", "Haratha"], dangers=["verletzte Diener werden vernichtet"],
         bias=dict(face=1.3), source=SRC_ICY),
    dict(id="rexxar_misha", match=["Story_02_Misha"], name="Misha", chapter="Rexxar", order=3,
         start_hp=30, boss_power="Tobsucht (jede Runde): 1–3 Schaden an 2 zufälligen Dienern",
         goal="Kein normales Spiel: Töte die Fiese Bärenfalle (2/40) auf seiner Seite, bevor der Boss stirbt - sie schadet ihm jede Runde",
         tips=["Frühe Diener sterben an Wildem Wüten: erst Karten ziehen (Findigkeit des Aasfressers, Tauchender Greif).",
               "Ansturm-Diener sofort in die Bärenfalle laufen lassen; Diener mit 3+ Leben (Savannen-Hochmähne) normal spielen. Schwache Diener zusammen mit der Heldenkraft ausspielen, damit sie überleben.",
               "Sorge dich nicht um sein Leben: er heilt sich mit Wildem Heulen und Klaue."],
         mulligan=["Springpaw", "Findigkeit des Aasfressers", "Tauchender Greif"], dangers=["Boss stirbt vor der Falle = verloren"],
         bias=dict(face=0.15, priority={"Fiese Bärenfalle": 3.0}), source=SRC_ICY),
    dict(id="rexxar_quilboar", match=["Story_02_Quilboar"], name="Wilder Stacheleber", chapter="Rexxar", order=4,
         start_hp=30, boss_power="Kommt alle her! (2 Mana): ruft 2 Jäger der Stacheleber (4/2) herbei",
         goal="Misha (Heldenkraft Misha rufen) immer auf dem Brett haben; Brett aufbauen und kaum tauschen",
         tips=["Du startest mit Mogrin 0/14, der nicht angreift - er muss nicht sterben.",
               "Viele seiner Diener haben Ansturm oder Tarnung und tauschen trotzdem in dein Brett: nur sehr effiziente Trades machen (z. B. 2 Angriff in einen Stacheleber-Jäger).",
               "Misha rufen, wenn sie fehlt; mit ihr im Spiel nicht erneut rufen (Zweiteffekt schwach)."],
         mulligan=["Überwältigen", "Findigkeit des Aasfressers", "Biest mit 3 Mana"], dangers=["Ansturm/Tarnung auf seiner Seite"], source=SRC_ICY),
    dict(id="rexxar_darkscale", match=["Story_02_Darkscale"], name="Lady Dunkelschuppe", chapter="Rexxar", order=5,
         start_hp=40, boss_power="Tornado (2 Mana): 4 Schaden an einen Diener, Überschuss wandert weiter (wächst mit Zauberschaden)",
         goal="Sein Brett (Zauberschaden-Schamane) jede Runde sauber halten und langsam herunterschleifen",
         tips=["Misha jede Runde zu Beginn rufen, wenn sie nicht lebt - das lockt auch seinen Tornado an.",
               "Kleine Mage-Zauber (Spiegelbild, Gefrierzaubertrank) wirken zu Zugbeginn automatisch.",
               "Ist sein Brett unter Kontrolle, Mana in zusätzliche Diener stecken."],
         mulligan=["Höllenkeiler", "Raptorjunges", "Phasenpirscher"], dangers=["Zauberschaden verstärkt Tornado"], bias=dict(defensive=True),
         source=SRC_ICY),
    dict(id="rexxar_khiragg", match=["Story_02_Centaur"], name="Khiragg", chapter="Rexxar", order=6,
         start_hp=40, boss_power="Entführen! (2 Mana): steckt einen deiner Diener (außer Misha) in einen Prall gefüllten Sack",
         goal="Immer Misha UND einen weiteren Diener auf dem Brett haben; Säcke zuerst töten, um die Diener zu befreien",
         tips=["Mindestens 1 anderer Diener neben Misha am Rundenende zwingt ihn, 2 Mana für Entführen zu verschwenden.",
               "Säcke zuerst vernichten (befreit deinen Diener), dann den Rest, dann das Gesicht.",
               "Tundra-Rhino (Ansturm für Diener aus der Hand, auch für Misha und befreite Diener) ist die Siegkarte."],
         mulligan=["Höllenkeiler", "Raptorjunges", "Phasenpirscher"], dangers=["Diebes-Schurke mit Tempo (Vendetta)"],
         bias=dict(priority={"Prall gefüllter Sack": 1.8}), source=SRC_ICY),
    dict(id="rexxar_daelin", match=["Story_02_Daelin"], name="Daelin Prachtmeer", chapter="Rexxar", order=7,
         start_hp=50, boss_power="Kriegsschiff entsenden (4 Mana): Kriegsschiff von Kul Tiras (2/6)",
         goal="Bis Runde 4 bereit sein, das Kriegsschiff zu töten (Tödlicher Schuss oder 2+ Schaden mit Axtwurf), und das Tempo halten",
         tips=["Hast du das erste Kriegsschiff überstanden, bist du im Tempo vorn: weiter Tempo machen, denn er überholt dich später mit Wert (Auge des Sturms, Wandelnder Brunnen)."],
         mulligan=["Adlerhornbogen", "Tödlicher Schuss", "Hyänenalpha"], dangers=["Kriegsschiff in Runde 4"],
         bias=dict(priority={"Kriegsschiff von Kul Tiras": 1.8}), source=SRC_ICY),
    dict(id="rexxar_gorgrom", match=["Story_02_Gorgrom"], name="Drachenfresser Gorgrom", chapter="Rexxar", order=8,
         start_hp=50, boss_power="Monströses Wachstum (2 Mana): 2 Rüstung (3, wenn du weniger als 5 hast)",
         goal="Langer Kampf gegen viel Rüstung: auf lange Sicht planen, Heldenkraft (Axtwurf II) voll nutzen",
         tips=["Diener mit mindestens 3 Leben halten (Blutschlund-Rohlinge); bleibt einer stehen, mit Bloatbat/Todesröcheln aufräumen.",
               "Gronn-Falle aufs Brett stellen und nicht übermäßig Karten ziehen (Fatigue möglich)."],
         mulligan=["Phasenpirscher", "Findigkeit des Aasfressers", "Tierbegleiter"], dangers=["Rohlinge, Kontrolle-Krieger"],
         bias=dict(hp_bonus=1.0), source=SRC_ICY),

    dict(id="garrosh_geyah", match=["Story_03_Geyah"], name="Großmutter Geyah", chapter="Garrosh", order=1,
         start_hp=30, boss_power="Weiser Rat (2 Mana): heilt alle Diener um 2",
         goal="Normales Spiel wie auf der Rangliste: Brett kontrollieren, Waffen und Diener für Werttrades nutzen",
         tips=["Kein Comeback-Mechanismus bei ihr: einfach Kontrolle und langsam abbauen."],
         mulligan=["Schlachtbeil", "Knochenbrecher-Raufbold", "Clan-Krieger"], dangers=[], source=SRC_ICY),
    dict(id="garrosh_rehgar", match=["Story_03_Rehgar"], name="Rehgar Erdenwut", chapter="Garrosh", order=2,
         start_hp=30, boss_power="Ausgewogenes Urteil: ruft jede Runde einen ungeraden oder geraden Totem herbei",
         goal="Angriffswerte deiner Diener ungerade halten, Totems jede Runde töten",
         tips=["Ungerade Totems kannst du mit 'Verstärken' ausgleichen, gerade Totems können dir Diener nehmen.",
               "Brett kontrollieren und dann Gesicht."],
         mulligan=["Schlachtbeil", "Knochenbrecher-Raufbold", "Clan-Krieger"], dangers=["gerade Totems gegen deine Diener"], source=SRC_ICY),
    dict(id="garrosh_zarzhet", match=["Story_03_Zarzhet"], name="Unterkönigin Zarzhet", chapter="Garrosh", order=3,
         start_hp=30, boss_power="Dunkle Umwandlung (2 Mana): 2 Schaden an einen zufälligen Diener; stirbt er, kommt ein Ghul",
         goal="Aggressiv spielen, um vor ihren späten Zaubern (Armee der Toten, Heuschreckenschwarm) zu gewinnen",
         tips=["Diener mit mehr als 2 Leben legen. Eier, Ghule und Ähnliches ignorieren, nur Abscheulichkeiten gezielt töten (zuerst andere Todesröcheln-Diener räumen)."],
         mulligan=["Horde-Rüstungsschmied", "Rasender Berserker"], dangers=["späte Flächenzauber"], bias=dict(face=1.2), source=SRC_ICY),
    dict(id="garrosh_fire", match=["Story_03_FireElemental"], name="Sengender Feuerelementar", chapter="Garrosh", order=4,
         start_hp=30, boss_power="Einäschern (jede Runde gratis): 1 Schaden an allen Feinden pro Elementar auf seiner Seite",
         goal="Jeden Elementar sofort töten und Elementarrisse sofort beseitigen, sonst schlägt Einäschern hart zu",
         tips=["Peon beschwören II nutzen, um schwache Elementare per Ansturm zu räumen.",
               "Ist sein Brett leer, Mana in deine Diener mit den meisten Leben stecken."],
         mulligan=["Zwang", "Streitaxt von Warsong"], dangers=["Elementarrisse beschwören laufend Elementare"],
         bias=dict(priority={"Elementarriss": 2.5}, defensive=True), source=SRC_ICY),
    dict(id="garrosh_cairne", match=["Story_03_Cairne"], name="Häuptling Cairne Bluthuf", chapter="Garrosh", order=5,
         start_hp=40, boss_power="Kriegsdonner (jeden Zug automatisch): 1 Schaden an allen Feinden",
         goal="Spott-Diener räumen (nicht bei 1 Leben stehen lassen), ab Runde 6 Gorehowl dauerhaft ausgerüstet halten",
         tips=["Er spielt passiv, gelegentlich einen Spott-Diener; Kontrollkrieger mit Flächenräumern (Pfad der Verwüstung, Brawl)."],
         mulligan=["Spielmacher", "Clan-Trainer", "Kor'kron-Elite"], dangers=["Kriegsstampfer auf 1-Leben-Diener"], source=SRC_ICY),

    dict(id="uther_alonsus", match=["Story_04_Alonsus"], name="Alonsus Faol", chapter="Uther", order=1,
         start_hp=30, boss_power="Heiliges Gebet (2 Mana): heilt einen Diener und den Helden um 1",
         goal="Sein Deck hat kaum Wert: Brett kontrollieren, tauschen, bis ihm die Karten ausgehen",
         tips=["Heiliger Champion beendet das Spiel schnell, weil beide heilen."],
         mulligan=["Nordhain-Kleriker", "Müder Rekrut"], dangers=[], source=SRC_ICY),
    dict(id="uther_blademaster", match=["Story_04_Blademaster"], name="Schwarzfels-Klingenmeister", chapter="Uther", order=5,
         start_hp=40, boss_power="Klingensturm (1 Mana): 3 Schaden an deinen Diener mit dem meisten Angriff, 1 an alle anderen",
         goal="Keine unnötigen Diener früh spielen; ab Runde 4 Leuchtbringer ausrüsten und einen starken Diener per Göttlichem Schild schützen",
         tips=["Den Diener mit dem Waffenschlag mit Göttlichem Schild schützen, um Klingensturm (3 Schaden auf den stärksten Diener) abzufangen."],
         mulligan=["Lordaeron-Begleiter", "Buch der Weisheit"], dangers=["Klingensturm jede Runde"], bias=dict(defensive=True), source=SRC_ICY),
    dict(id="uther_iceblade", match=["Story_04_Iceblade"], name="Venim Eisklinge", chapter="Uther", order=6,
         start_hp=40, boss_power="Infektion (am Zugende): verwandelt einen nicht-legendären Diener von dir in ein Skelett 1/1 und übernimmt es",
         goal="Nie einzelne Diener früh spielen (sie sterben an Infektion); ab Runde 3 Leuchtbringer II ausrüsten, dann mehrere Diener auf einmal legen",
         tips=["Luftangriff und Gegen die Dunkelheit stehen helfen beim Fluten des Bretts."],
         mulligan=["Lordaeron-Begleiter", "Buch der Weisheit"], dangers=["Infektion nimmt dir einzelne Diener"], source=SRC_ICY),
    dict(id="uther_malganis", match=["Story_04_MalGanis"], name="Mal'Ganis", chapter="Uther", order=7,
         start_hp=50, boss_power="Gunst des Nathrezim (passiv): seine äußersten Diener bekommen am Zugende +3/+3",
         goal="Maximal aggressiv: Stats aufs Brett, jeden seiner Diener sofort entfernen (Göttlicher Sturm, Waffen)",
         tips=["Hand mit Silberhand-Kreuzfahrer nachfüllen, wenn das Spiel länger dauert."],
         mulligan=["Lordaeron-Begleiter", "Unerschütterlicher Glaube", "Paladin des Lichts"], dangers=["große Dämonen"], bias=dict(face=1.2), source=SRC_ICY),

    dict(id="anduin_moira", match=["Story_05_Moira"], name="Moira Thaurissan", chapter="Anduin", order=3,
         start_hp=30, boss_power="Königliches Gefolge (3 Mana): ruft einen Arenagast 3/3 herbei",
         goal="Mana effizient nutzen und Infiltratorenfernglas jede Runde ab Runde 2 einsetzen (zeigt, was sie zieht, und verteuert es)",
         tips=["Mit dem Fernglas sorgst du dafür, dass sie die gegen dich nutzloseste Karte zieht."],
         mulligan=["Eifriger Novize", "Psychische Beschwörerin", "Hohepriester Rohan"], dangers=[], source=SRC_ICY),

    # ---------------------------------------------------------------- Galakronds Erwachen (Icy Veins, Jan./Feb. 2020; Werte Normal / Heroic)
    dict(id="drga_chenvaala", match=["DRGA_BOSS_25h"], name="Chenvaala", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Schneesturm (3 Mana): ruft einen eingefrorenen Elementar 4/4 herbei",
         goal="Sein Freeze-Deck beherrschen: Brett kontrollieren und Frostbrand/Schockfrost nicht ins Leere laufen lassen",
         tips=["Schock-Einfrieren (Snap Freeze) räumt deine großen Diener: nicht alles in einen Diener stecken.",
               "Normal: Mit der billigen Heldenkraft den Lebenden Drachenatem des Gegners stehlen - dann bist du immun gegen Einfrieren.",
               "Heroic: Er spielt 4/4 für 1 Mana; spiele selbst den Lebenden Drachenatem und beschütze ihn."],
         dangers=["Einfrieren + Schockfrost"], source=SRC_ICY),
    dict(id="drga_drboom", match=["DRGA_BOSS_05h", "DRGA_BOSS_05h2"], name="Dr. Bumm", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="RUFT DIE BOTS HERBEI! (2 Mana): bekommt einen zufälligen überstatteten Mech",
         goal="Auf einen Weg zum Sieg setzen, nicht auf Wertspiel: seine Heldenkraft liefert ihm ständig Mechs",
         tips=["Normal: Er hat wenig Interaktion (Rammgeschwindigkeit), Brett kontrollieren und Rest-Schaden ins Gesicht. Die Boomship und der Bumm-Plünderer sind seine Tempo-Karten.",
               "Heroic: Er startet mit 30 Rüstung (Plattenbrecher hilft), viele Magnetische Mechs - Stille/Sap/Eiskalte Falle gegen Magnetische. Vorsicht vor Bomben, viel Kartenziehen ist riskant."],
         dangers=["Bomben im Deck (Heroic)", "Magnetische Mechs"], bias=dict(face=1.1), source=SRC_ICY),
    dict(id="drga_reno", match=["DRGA_BOSS_01h", "DRGA_BOSS_01h3", "DRGA_BOSS_01h4", "DRGA_BOSS_01h2"], name="Reno Jackson (Der unglaubliche Reno)", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Gatlingmagie (passiv): wirkt nach jedem Zauber einen weiteren zufälligen Zauber",
         goal="Nicht zu viele Diener aufs Brett legen: zufällige Einzelziel-/Flächenzauber treffen sonst dich",
         tips=["Normal: Hand mit der Heldenkraft auffüllen, Bomben (Schraubenschlüssel-Excalibur, Aufziehgoblin) können ihn töten, auch wenn dein Brett geräumt wird.",
               "Heroic: Highlander-Deck mit Zephrys; solange du nicht überrannt wirst, reicht der Zufallsschaden nicht für einen Sieg gegen dich."],
         dangers=["unberechenbare Zufallszauber"], bias=dict(defensive=True), source=SRC_ICY),
    dict(id="drga_finley", match=["DRGA_BOSS_03h", "DRGA_BOSS_03h2", "DRGA_BOSS_03h2_H"], name="Sir Finley", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Speerspitze (Normal 2, Heroic 1 Mana): ein Diener bekommt Eifer und Gottesschild",
         goal="Er flutet das Brett mit billigen Dienern (Heroic: Murlocs): große Lebenswerte und Wert-Trades, Flächenschaden erst nach neuen Dienern",
         tips=["Normal: Dein Deck ist stärker - tausche Wert gegen Wert, keine Burst-Gefahr (kein Wilder Brüller/Blutrausch).",
               "Heroic: viele Flächenräumer, Lebensbuffs (Göttlicher Geist, Velens Auserwählter), nur Toxfin als Notfall-Entfernung."],
         dangers=["Brett wird geflutet"], source=SRC_ICY),
    dict(id="drga_dawnshatter", match=["DRGA_BOSS_18h"], name="Hochkultistin Dämmerschlag", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Drachenknochenritual (passiv): liefert ihr nach jedem Drachen viel Wert",
         goal="Das Brett sichern (sie hat keinen Flächenschaden) und große Diener ausspielen",
         tips=["Normal: Deine passive Drachenblut-Heldenkraft ist zu deinem Vorteil, solange viele Diener liegen, wenn deine Drachen sterben.",
               "Heroic: 30 Rüstung, Atem der Träume/Kerzenatem rampen sie; ihr fehlt harte Entfernung - große Diener schnell ausspielen."],
         dangers=["Rampe und Kartenziehen"], source=SRC_ICY),
    dict(id="drga_lazul", match=["DRGA_BOSS_09h", "DRGA_BOSS_09h2"], name="Lazul, die Puppenspielerin", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Weissagung (1 Mana): entdeckt eine Kopie einer Karte aus deinem Deck",
         goal="Zweiphasenkampf: in Phase 1 schnell gewinnen (Boss 30 Leben), dann Go'rath (50 Leben, 5 Mana, Tentakel-Brett) kontrollieren",
         tips=["Vor dem Phasenwechsel eine Antwort auf das Tentakel-Brett bereit haben (Blitzsturm oder mehrere Diener, die sofort angreifen).",
               "Heroic: Schattenwahnsinn, Trank des Wahnsinns und Puppenspieler beachten - Brett vorsichtig aufbauen."],
         dangers=["Tentakel-Brett in Phase 2", "Schattenwahnsinn (Heroic)"], source=SRC_ICY),
    dict(id="drga_gorath", match=["DRGA_BOSS_21h"], name="Go'rath", chapter="Galakronds Erwachen", order=0,
         start_hp=50, boss_power="Aus der Tiefe (2 Mana): ruft ein zufälliges Tentakel von Go'rath herbei",
         goal="Phase 2 gegen Lazul: ein Brett voller Tentakel räumen, bevor sie dich überrennen oder dir die Karten ausgehen",
         tips=["Du hast eine Uhr: Tentakel schnell töten und dann den Boss."], dangers=["Tentakel-Brett"], source=SRC_ICY),
    dict(id="drga_hagatha", match=["DRGA_BOSS_06h", "DRGA_BOSS_06h2"], name="Hagatha die Rachsüchtige", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Hand der Sumpfkönigin (2 Mana): verwandelt einen Diener in einen Diener mit +1 Mana (Evolve)",
         goal="Das Brett jede Runde unter Kontrolle halten: ihre Heldenkraft braucht Ziele",
         tips=["Eigene Heldenkraft (Atem des Lebens) nutzen, um niedrige Leben zu buffen oder zu heilen.",
               "Heroic: Sie kann das Brett nur mit Blitzsturm und Rückentwicklung bereinigen - Entfernung und Diener kombinieren."],
         dangers=["Wertspiel mit Evolve"], source=SRC_ICY),
    dict(id="drga_askaara", match=["DRGA_BOSS_26h"], name="Drachenmagierin Askaara", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Drachenaffinität / Flammenaffinität (wechselnd, passiv): Mana-Rabatt auf Drachen bzw. Zauber",
         goal="Brett kontrollieren: Ihr Tempo ist hoch, sie bekommt wenig Interaktion; tötest du jeden Diener, hat sie nur Zufallszauber",
         tips=["Normal: Alle Diener töten zwingt sie aus dem Spiel. Heroic: effizientere Karten, aber keine harte Entfernung - große Tempo-Diener oder jeden Diener entfernen.",
               "Drachenschmuggler und Drachentöter sind starke Beigaben."],
         dangers=["Tempo durch Rabatte"], source=SRC_ICY),
    dict(id="drga_explorers", match=["DRGA_BOSS_27h"], name="Die leitenden Forscher", chapter="Galakronds Erwachen", order=0,
         start_hp=40, boss_power="Gemeinsam stark (Normal 1 Mana, Heroic frei): mischt 2 zufällige Forscherschätze in ihr Deck",
         goal="Schnell Druck machen, bevor viele Schätze gezogen werden",
         tips=["Normal: Sie verschwendet Mana für die Heldenkraft - Tempo nutzen, Brett füllen.",
               "Heroic: 40 Leben +20 Rüstung, Heldenkraft gratis: schneller spielen. Einzige Entfernung: Aldor-Friedenswächter und Schätze wie das Titanengeschmiedete Greifhaken."],
         dangers=["Schätze und Quests"], bias=dict(face=1.15), source=SRC_ICY),
    dict(id="drga_nithogg", match=["DRGA_BOSS_20h"], name="Nithogg", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Sturmgrimm (3 Mana, Heroic billiger): 2 Schaden an einen zufälligen feindlichen Diener",
         goal="Brett kontrollieren, gegen Sturmgrimm einen hochlebigen Diener oder mehrere Diener halten",
         tips=["Er hat nur eine begrenzte Zahl an Dienern und keine harte Entfernung (Heroic): Kontrolle und große Diener gewinnen."],
         dangers=["Überladen-Midrange mit Entfernung"], source=SRC_ICY),
    dict(id="drga_talritha", match=["DRGA_BOSS_23h", "DRGA_BOSS_23h2"], name="Drachenreiterin Talritha", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Drachenblut (passiv): alle Diener +1/+1, wenn ein befreundeter Drache stirbt",
         goal="Wert-Trades; tötest du ihre Drachen, buffst du dich mit",
         tips=["Heroic: Nachtbane-Tempelritter flutet das Brett; sie hat keinen Flächenschaden - schneller fluten und Drachenblut gegen sie nutzen."],
         dangers=[], source=SRC_ICY),
    dict(id="drga_dragonflights", match=["DRGA_BOSS_32h"], name="Die Drachenschwärme", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Drachenflamme (2 Mana): 2 Schaden an einen Feind oder Heilung",
         survive=10, goal="Der Boss ist nicht zu verletzen: Überlebe 10 Runden",
         tips=["Frühe Runden überleben, Verzögerungs-Karten (Sap, Ausweichen) für die letzten Runden aufheben. Heroic: nur Entfernung und Heilung spielen."],
         dangers=["Rampe durch Atem der Träume"], bias=dict(defensive=True), source=SRC_ICY),
    dict(id="drga_wanderer", match=["DRGA_BOSS_30h", "DRGA_BOSS_30h2", "DRGA_BOSS_31h", "DRGA_BOSS_31h2", "DRGA_BOSS_31h3"], name="Der Wanderer / Die Windschatten", chapter="Galakronds Erwachen", order=0,
         start_hp=30, boss_power="Kanonen schussbereit! (2 Mana): eine Kanone, die am Zugende automatisch schießt",
         goal="Luftschiff-Duell wie das Schach-Event: Auto-Angriff der Kanonen beachten",
         tips=["Normal hast du ein fast identisches Deck: Positionen planen, eine ungerade Differenz an Dienern lässt deine Kanonen 2 Ziele treffen.",
               "Heroic: Er hat mehr Mana, du ein eigenes Deck: Flächenräumer im Mittelspiel, große Diener, da er keine harte Entfernung hat."],
         dangers=["Auto-Angriffe der Kanonen"], source=SRC_ICY),

    # ---------------------------------------------------------------- Eine Nacht in Karazhan (Abenteuer 2016, eigene Decks)
    # Quellen: Icy Veins (Boss-Guides, 2016), Kartentexte (HearthstoneJSON). Werte: Normal / Heroic.
    # Prolog (Malchezaar), Schach und Free Medivh! spielen mit festem Deck, der Rest mit deiner Sammlung.
    dict(id="kara_malchezaar", match=["KARA_00_01", "KARA_00_01H", "KARA_13_06", "KARA_13_06H"], name="Prinz Malchezaar", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Legion (2 Mana): ruft einen Abyssal 6/6 herbei (Heroic: zwei)",
         goal="Jede Runde kommt ein 6/6 - schnell gewinnen, sein Brett mit Flächenschaden/Tauschen kontrollieren",
         tips=["Leben: Prolog 30 (+30 Rüstung), Heroic 60 (+60 Rüstung); er startet mit nur 5 Mana.",
               "Prolog (festes Medivh-Deck): Wächter-Beschwörung (Guardian's Evocation) gibt Mana für die 6/6; Arkane Macht + Arkane Explosion/Geschosse räumen auf; Mysteriöse Rune sperrt ihn.",
               "Free Medivh! (letzter Boss): erst Nazra Wildaxt (15 Leben), dann Malchezaar - er wirkt sofort Twisting Nether (räumt dein Brett). Mit vielen Todesröcheln oder einer Gewinnkarte (N'Zoth) auf der Hand in den Kampf gehen und Nazra möglichst lange hinhalten."],
         dangers=["ein neuer 6/6 pro Runde (Heroic zwei)", "Twisting Nether nach dem Wechsel in Free Medivh!"],
         bias=dict(priority={"Abyssal": 1.3}), source=SRC_ICY),
    dict(id="kara_hexe", match=["KARA_04_01h", "KARA_04_01heroic"], name="Die böse Hexe", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Tornado (0 Mana, automatisch): 100 Schaden an dich, sobald Dorothee tot ist",
         goal="Dorothee (0/10, auf deiner Seite) am Leben halten - stirbt sie, tötet dich die Hexe sofort",
         tips=["Diener LINKS von Dorothee bekommen Ansturm, Diener RECHTS von ihr Spott: hohe Lebenswerte nach rechts (schützen sie), hohe Angriffswerte nach links.",
               "Normal: 30 Leben, Heroic: 50 (+15 Rüstung). Heroic: Ab Runde 8 werden ihre gezogenen Karten zu Twisting Nether - bis dahin gewinnen (aggressiv) oder Dorothee wiederbeleben (Ahnengeist)."],
         dangers=["Dorothee stirbt = Niederlage", "Heroic ab Runde 8: Twisting Nether"], bias=dict(defensive=True), source=SRC_ICY),
    dict(id="kara_wolf", match=["KARA_05_01h", "KARA_05_01hheroic", "KARA_05_01b"], name="Der große böse Wolf", chapter="Karazhan", order=0,
         start_hp=20, boss_power="Furchteinflößend (passiv): Normal sind DEINE Diener 1/1 und kosten (1); Heroic kosten SEINE Diener (1) mit normalen Werten",
         goal="Normal: viele 1/1 spielen, Kampfschrei-/Todesröcheln-Diener und Zauber nutzen. Heroic: nicht um das Brett kämpfen",
         tips=["Normal: Wert kommt aus Kampfschrei, Todesröcheln, Kartenziehen und Buffs - Dienerwerte sind egal.",
               "Heroic: Er startet mit 3 Großmütterchen und spielt Diener für 1 Mana (20 Leben +15 Rüstung). Freeze-Mage oder N'Zoth mit Todesröcheln (Tirion, Sylvanas) sind die Wege."],
         dangers=["Heroic: sein Brett für 1 Mana pro Karte"], source=SRC_ICY),
    dict(id="kara_julianne", match=["KARA_06_02", "KARA_06_02heroic"], name="Julianne", chapter="Karazhan", order=0,
         start_hp=15, boss_power="Wahre Liebe: ruft Romulo (4/2) herbei, wenn er nicht lebt (Normal 4 Mana, Heroic 0 Mana und automatisch)",
         goal="Romulo töten, dann im selben Zug Julianne treffen: Solange Romulo lebt, ist sie unverwundbar",
         tips=["Normal: kleine saubere Entfernung für Romulo genügt, ihre Heldenkraft ist zu teuer.",
               "Heroic: Romulo kommt jede Runde wieder (15 Leben +15 Rüstung) - Stille, Saboteur (Heldenkraft teurer) oder Ansturm-Schaden im selben Zug."],
         dangers=["Romulo schlägt jede Runde für 4"], bias=dict(face=0.5, priority={"Romulo": 3.0}), source=SRC_ICY),
    dict(id="kara_golem", match=["KAR_A02_12", "KAR_A02_12H"], name="Tafelsilbergolem", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Zu Tisch! (0 Mana, automatisch): ruft einen Teller 1/1 herbei (Heroic: zwei)",
         goal="Seine 1/1-Teller sofort räumen, bevor er sie mit Ansturm/Schaden-Buffs aufwertet",
         tips=["Flächenschaden (Arkane Explosion, Wirbelwind-Effekte) ist der Schlüssel; Heroic: 30 Leben +15 Rüstung."],
         dangers=["gebuffte Teller (Ansturm)"], bias=dict(priority={"Teller": 1.2}), source=SRC_ICY),
    dict(id="kara_spiegel", match=["KAR_A01_01", "KAR_A01_01H"], name="Der Zauberspiegel", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Spiegelbilder (passiv): von jedem ausgespielten Diener entsteht eine 1/1-Kopie - Normal für den Spieler, Heroic nur für den Spiegel",
         goal="Normal: Du bekommst auch Kopien - Zoo/Wert-Diener nutzen. Heroic: nur der Spiegel bekommt Kopien, jeder Diener hilft ihm",
         tips=["Heroic: 30 Leben +15 Rüstung. Diener mit negativem Effekt für ihn (Doomsayer, Instabiler Ghul, Majordomus) sind stark."],
         dangers=["Heroic: jede gespielte Karte gibt ihm einen 1/1"], source=SRC_ICY),
    dict(id="kara_schach", match=["KAR_a10_Boss1", "KAR_a10_Boss1H", "KAR_a10_Boss2", "KAR_a10_Boss2H"], name="Schach (Weißer/Schwarzer König)", chapter="Karazhan", order=0,
         start_hp=20, boss_power="Schummeln (2 Mana): vernichtet deinen ganz linken Diener",
         goal="Feste Decks, 20 Leben für beide: starke Figuren nach RECHTS, links eine billige Figur als Opfer",
         tips=["Diener greifen den gegenüberliegenden Diener an; steht ein Diener zwischen zwei gegnerischen, trifft er beide.",
               "Heroic: Deine Heldenkraft verschiebt nur einen Diener nach links (1 Mana, mehrfach). Die KI setzt ihre Figuren immer ganz links - nutze das, um das Brett für sie schlecht zu stellen. Nur 15 Karten: nicht zu früh das Brett fluten."],
         dangers=["Schummeln vernichtet deinen linken Diener"], bias=dict(face=1.1), source=SRC_ICY),
    dict(id="kara_kurator", match=["KARA_07_01", "KARA_07_01heroic"], name="Der Kurator", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Beschützer der Galerie (passiv): sein Held hat Spott",
         goal="Mit dem Helden-Spott kannst du nicht in seine Diener tauschen: ALLE Angriffe gehen auf den Helden - aggressiv und früh",
         tips=["Normal 30 Leben: ein aggressiver Anfang (Zoo, Aggro-Schamane/Jäger/Druide) gewinnt das Rennen.",
               "Heroic 40 Leben +15 Rüstung: Bestien-Druide (Menagerie-Wächter) oder Tempo-Mage/Miracle-Schurke mit Entfernung."],
         dangers=[], bias=dict(face=1.5), source=SRC_ICY),
    dict(id="kara_nightbane", match=["KARA_11_01", "KARA_11_01heroic"], name="Schrecken der Nacht (Nightbane)", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Manasturm (passiv): beide Spieler beginnen mit 10 Manakristallen",
         goal="10 Mana ab Runde 1: teure Diener sofort legen; Deck voller Wert-Diener (Legendäre) gewinnt",
         tips=["Er spielt Todesschwinge: nicht das ganze Brett ohne Antwort (Großwildjäger o. Ä.) auf der Hand überentwickeln. Heroic: 30 Leben +15 Rüstung."],
         dangers=["Todesschwinge räumt ein überentwickeltes Brett"], source=SRC_ICY),
    dict(id="kara_illhoof", match=["KARA_09_01", "KARA_09_01heroic"], name="Terestian Siechhuf", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Dunkler Pakt (passiv): immun gegen Schaden, außer durch das Todesröcheln seiner Widerlichen Wichtel",
         goal="Töte viele Wichtel auf einmal (Flächenschaden): ihre Todesröcheln verletzen ihn. Direkter Schaden auf den Boss ist wirkungslos",
         tips=["Normal: Wichtel sind 1/1 und kein Risiko - Wirbelwind-/Schwerthieb-/Arkane-Explosion-Effekte. Heroic: 40 Leben, Wichtel 2/2 - sehr defensiv spielen oder Wichtel stehlen (Priester)."],
         dangers=["Heroic: 2/2-Wichtel bauen Druck auf"], bias=dict(face=0.05, priority={"Widerlicher Wichtel": 1.8}), source=SRC_ICY),
    dict(id="kara_netherspite", match=["KARA_08_01", "KARA_08_01H"], name="Nethergroll (Netherspite)", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Netherzorn (automatisch): Held +3 Angriff pro Zug (Heroic +8, 1 Mana); Portale auf deiner Seite buffen ihn, wenn du sie nicht mit Dienern blockst",
         goal="Spott-Diener gegen seine Heldenangriffe, Portale mit Dienern blocken (dann bekommst DU die Buffs), links Druck machen",
         tips=["Sein Deck hat keine Diener - Entfernungszauber sind verzichtbar.",
               "Heroic: ohne Spott-Diener (Schildträger) trifft er dich in Runde 1 für 18 Schaden. 30 Leben +15 Rüstung."],
         dangers=["Heldenangriff mit +3 / +8 Angriff"], bias=dict(defensive=True), source=SRC_ICY),
    dict(id="kara_aran", match=["KARA_12_01", "KARA_12_01H"], name="Arans Schemen", chapter="Karazhan", order=0,
         start_hp=30, boss_power="Leylinien (passiv): Zauberschaden +3 für beide (Heroic +5)",
         goal="Der Zauberschaden gilt für beide - Zauber setzen, aber mit wenigen/ohne Diener rechnen",
         tips=["Sein Deck lebt von Zaubern und Geheimnissen, vor allem 'Flammenkranz' (Flame Wreath) fegt dein Brett: Geheimnisse zerstören (Kezan-Mystiker, Geheimnisfresser) oder auf Diener verzichten.",
               "Heroic: 30 Leben +15 Rüstung; viele Schadenszauber und kein Dienerplan."],
         dangers=["Flammenkranz gegen dein Brett"], bias=dict(defensive=True, secret_p=0.5), source=SRC_ICY),
    dict(id="kara_nazra", match=["KARA_13_01", "KARA_13_01H"], name="Nazra Wildaxt", chapter="Karazhan", order=0,
         start_hp=15, boss_power="Die Horde (2 Mana): ruft einen Orc 3/2 herbei (Heroic: 3/3 mit Ansturm)",
         goal="Falsches Portal in Free Medivh!: nur 15 Leben - Brett kontrollieren, dann lange genug hinhalten, bis du für Malchezaar bereit bist",
         tips=["Danach folgt Malchezaar mit Twisting Nether: Todesröcheln-Diener oder eine Gewinnkarte (N'Zoth) vorbereiten."],
         dangers=["Heroic: Orcs mit Ansturm"], bias=dict(face=1.0), source=SRC_ICY),
]
